version: "3"
services:
  nginx:             # nginx 컨테이너 이름 (원하는 이름)
    image: flcat/nginx:0.4
    ports:
      - 80:80
    container_name: test_nginx

    depends_on:
      - web
      - api
    extra_hosts:
      - "host.docker,internal:host-gateway"
  web:
    image: flcat/web:0.2
    ports:
      - 8081:8081
    container_name: test_docker-web
  api:
      image: flcat/api:0.2
      ports:
        - 8080:8080
      container_name: test_docker-api