name : remote ssh commands
on: [push]
jobs:
 build:
         name: Build
         runs-on: amazon-linux2-latest
         steps:
                - name: executing remote ssh commands using key-file
                  uses: flcat/ssh-action@main
                  with:
                        host: ${{ secrets.HOST }}
                        username: ec2-user
                        key: ${{ secrets.KEY }}
                        script: |
                            if [ "$(docker ps -qa)" ]; then
                              sudo docker rm -f $(docker ps -qa)
                            fi
                            sudo docker pull ${{ secrets.DOCKER_REPO }}/flcat/test_docker
                            sudo docker pull ${{ secrets.DOCKER_REPO }}/nginx
                            sudo docker-compose -f /home/ec2-user/github/workspace/docker-compose.yml up -d
                            docker image prune -f
