name : remote ssh commands
on: [push]
jobs:
 build:
         name: Build
         runs-on: ["self-hosted", "Linux", "X64"]
         steps:
                - name: executing remote ssh commands using key-file
                  uses: appleboy/ssh-action@master
                  with:
                        host: ${{ secrets.HOST_DEV }}
                        username: ec2-user
                        key: ${{ secrets.KEY_DEV }}
                        script: |
                            if [ "$(docker ps -qa)" ]; then
                              sudo docker rm -f $(docker ps -qa)
                            fi
                            sudo docker pull ${{ secrets.DOCKER_REPO }}/flcat/test_docker
                            sudo docker pull ${{ secrets.DOCKER_REPO }}/nginx
                            sudo docker-compose -f /home/ec2-user/github/workspace/docker-compose.yml up -d
                            docker image prune -f
